# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vasp_set.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QDialog
import os
from ConfigParser import ConfigParser
import sys
sys.path.append('..')
from src.abinitio import Abinitio

class Ui_VASP_Set(QDialog):
    def __init__(self, parent=None):
        super(Ui_VASP_Set,self).__init__(parent)
        self.setupUi(self)
        self.setFixedSize(self.width(), self.height())
       
    def setupUi(self, VASP_Set):
        VASP_Set.setObjectName("VASP_Set")
        VASP_Set.resize(317, 288)
        self.tabWidget333 = QtWidgets.QTabWidget(VASP_Set)
        self.tabWidget333.setGeometry(QtCore.QRect(10, 0, 301, 251))
        self.tabWidget333.setObjectName("tabWidget333")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 216, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.IBRION = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.IBRION.setObjectName("IBRION")
        self.IBRION.addItem("")
        self.IBRION.addItem("")
        self.IBRION.addItem("")
        self.IBRION.addItem("")
        self.IBRION.addItem("")
        self.IBRION.addItem("")
        self.IBRION.addItem("")
        self.horizontalLayout.addWidget(self.IBRION)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.NSW = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.NSW.setMaximum(1000)
        self.NSW.setProperty("value", 500)
        self.NSW.setObjectName("NSW")
        self.horizontalLayout_2.addWidget(self.NSW)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.EDIFFG = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.EDIFFG.setObjectName("EDIFFG")
        self.horizontalLayout_3.addWidget(self.EDIFFG)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.PBE = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.PBE.setObjectName("PBE")
        self.PBE.addItem("")
        self.PBE.addItem("")
        self.PBE.addItem("")
        self.PBE.addItem("")
        self.PBE.addItem("")
        self.horizontalLayout_8.addWidget(self.PBE)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.ISYM = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.ISYM.setObjectName("ISYM")
        self.horizontalLayout_9.addWidget(self.ISYM)
        self.ISPIN = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.ISPIN.setObjectName("ISPIN")
        self.horizontalLayout_9.addWidget(self.ISPIN)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_11.addWidget(self.label_15)
        self.ISIF = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.ISIF.setMaximum(6)
        self.ISIF.setObjectName("ISIF")
        self.horizontalLayout_11.addWidget(self.ISIF)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.LREAL = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.LREAL.setChecked(True)
        self.LREAL.setObjectName("LREAL")
        self.horizontalLayout_12.addWidget(self.LREAL)
        self.LREAL_ = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.LREAL_.setObjectName("LREAL_")
        self.horizontalLayout_12.addWidget(self.LREAL_)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.tabWidget333.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(0, 140, 291, 81))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget_16 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_16.setGeometry(QtCore.QRect(0, 10, 286, 35))
        self.horizontalLayoutWidget_16.setObjectName("horizontalLayoutWidget_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_16)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_16)
        self.label.setObjectName("label")
        self.horizontalLayout_16.addWidget(self.label)
        self.ISTART = QtWidgets.QComboBox(self.horizontalLayoutWidget_16)
        self.ISTART.setEditable(False)
        self.ISTART.setObjectName("ISTART")
        self.ISTART.addItem("")
        self.ISTART.addItem("")
        self.ISTART.addItem("")
        self.horizontalLayout_16.addWidget(self.ISTART)
        self.horizontalLayoutWidget_17 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_17.setGeometry(QtCore.QRect(0, 40, 262, 35))
        self.horizontalLayoutWidget_17.setObjectName("horizontalLayoutWidget_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_17)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_17)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_17.addWidget(self.label_2)
        self.ICHARG = QtWidgets.QComboBox(self.horizontalLayoutWidget_17)
        self.ICHARG.setObjectName("ICHARG")
        self.ICHARG.addItem("")
        self.ICHARG.addItem("")
        self.ICHARG.addItem("")
        self.horizontalLayout_17.addWidget(self.ICHARG)
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 281, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.ALGO = QtWidgets.QComboBox(self.layoutWidget)
        self.ALGO.setObjectName("ALGO")
        self.ALGO.addItem("")
        self.ALGO.addItem("")
        self.ALGO.addItem("")
        self.ALGO.addItem("")
        self.ALGO.addItem("")
        self.horizontalLayout_4.addWidget(self.ALGO)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 30, 286, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.NELM = QtWidgets.QSpinBox(self.layoutWidget1)
        self.NELM.setMaximum(1000)
        self.NELM.setProperty("value", 500)
        self.NELM.setObjectName("NELM")
        self.horizontalLayout_5.addWidget(self.NELM)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.NELMIN = QtWidgets.QSpinBox(self.layoutWidget1)
        self.NELMIN.setMaximum(500)
        self.NELMIN.setProperty("value", 2)
        self.NELMIN.setObjectName("NELMIN")
        self.horizontalLayout_5.addWidget(self.NELMIN)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 60, 161, 32))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_7.addWidget(self.label_14)
        self.ENCUT = QtWidgets.QLineEdit(self.layoutWidget2)
        self.ENCUT.setObjectName("ENCUT")
        self.horizontalLayout_7.addWidget(self.ENCUT)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 100, 181, 31))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.EDIFF = QtWidgets.QLineEdit(self.layoutWidget3)
        self.EDIFF.setObjectName("EDIFF")
        self.horizontalLayout_6.addWidget(self.EDIFF)
        self.tabWidget333.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 10, 291, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayoutWidget_18 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_18.setGeometry(QtCore.QRect(10, 10, 280, 31))
        self.horizontalLayoutWidget_18.setObjectName("horizontalLayoutWidget_18")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_18)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_18)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_18.addWidget(self.label_13)
        self.ISMEAR = QtWidgets.QComboBox(self.horizontalLayoutWidget_18)
        self.ISMEAR.setObjectName("ISMEAR")
        self.ISMEAR.addItem("")
        self.ISMEAR.addItem("")
        self.ISMEAR.addItem("")
        self.ISMEAR.addItem("")
        self.ISMEAR.addItem("")
        self.ISMEAR.addItem("")
        self.ISMEAR.addItem("")
        self.horizontalLayout_18.addWidget(self.ISMEAR)
        self.horizontalLayoutWidget_19 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(10, 50, 141, 31))
        self.horizontalLayoutWidget_19.setObjectName("horizontalLayoutWidget_19")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_19)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_19.addWidget(self.label_17)
        self.SIGMA = QtWidgets.QLineEdit(self.horizontalLayoutWidget_19)
        self.SIGMA.setObjectName("SIGMA")
        self.horizontalLayout_19.addWidget(self.SIGMA)
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_19)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_19.addWidget(self.label_18)
        self.horizontalLayoutWidget_21 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_21.setGeometry(QtCore.QRect(190, 50, 95, 31))
        self.horizontalLayoutWidget_21.setObjectName("horizontalLayoutWidget_21")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_21)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget_21)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_22.addWidget(self.label_23)
        self.MP_order = QtWidgets.QLineEdit(self.horizontalLayoutWidget_21)
        self.MP_order.setEnabled(False)
        self.MP_order.setObjectName("MP_order")
        self.horizontalLayout_22.addWidget(self.MP_order)
        self.horizontalLayoutWidget_20 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_20.setGeometry(QtCore.QRect(10, 100, 171, 23))
        self.horizontalLayoutWidget_20.setObjectName("horizontalLayoutWidget_20")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_20)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_21 = QtWidgets.QLabel(self.horizontalLayoutWidget_20)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_20.addWidget(self.label_21)
        self.IVDW = QtWidgets.QComboBox(self.horizontalLayoutWidget_20)
        self.IVDW.setObjectName("IVDW")
        self.IVDW.addItem("")
        self.IVDW.addItem("")
        self.IVDW.addItem("")
        self.IVDW.addItem("")
        self.IVDW.addItem("")
        self.IVDW.addItem("")
        self.IVDW.addItem("")
        self.IVDW.addItem("")
        self.horizontalLayout_20.addWidget(self.IVDW)
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 130, 168, 22))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_21.addWidget(self.label_22)
        self.NWRITE = QtWidgets.QSpinBox(self.layoutWidget4)
        self.NWRITE.setEnabled(False)
        self.NWRITE.setMaximum(4)
        self.NWRITE.setProperty("value", 2)
        self.NWRITE.setObjectName("NWRITE")
        self.horizontalLayout_21.addWidget(self.NWRITE)
        self.horizontalLayoutWidget_22 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_22.setGeometry(QtCore.QRect(10, 160, 96, 31))
        self.horizontalLayoutWidget_22.setObjectName("horizontalLayoutWidget_22")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_22)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget_22)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_23.addWidget(self.label_24)
        self.core_num = QtWidgets.QSpinBox(self.horizontalLayoutWidget_22)
        self.core_num.setMaximum(1000)
        self.core_num.setProperty("value", 64)
        self.core_num.setObjectName("core_num")
        self.horizontalLayout_23.addWidget(self.core_num)
        self.horizontalLayoutWidget_23 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_23.setGeometry(QtCore.QRect(10, 200, 281, 31))
        self.horizontalLayoutWidget_23.setObjectName("horizontalLayoutWidget_23")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_23)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_26 = QtWidgets.QLabel(self.horizontalLayoutWidget_23)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_25.addWidget(self.label_26)
        self.vasp_path = QtWidgets.QLineEdit(self.horizontalLayoutWidget_23)
        self.vasp_path.setText("")
        self.vasp_path.setObjectName("vasp_path")
        self.horizontalLayout_25.addWidget(self.vasp_path)
        self.tabWidget333.addTab(self.tab_3, "")
        self.table_3 = QtWidgets.QWidget()
        self.table_3.setObjectName("table_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.table_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 201, 91))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_15.addWidget(self.label_20)
        self.generate_method = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.generate_method.setEnabled(False)
        self.generate_method.setObjectName("generate_method")
        self.generate_method.addItem("")
        self.generate_method.addItem("")
        self.generate_method.addItem("")
        self.horizontalLayout_15.addWidget(self.generate_method)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_14.addWidget(self.label_19)
        self.k_num = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.k_num.setEnabled(False)
        self.k_num.setMaximum(6)
        self.k_num.setObjectName("k_num")
        self.horizontalLayout_14.addWidget(self.k_num)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.coordinate_C = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.coordinate_C.setEnabled(False)
        self.coordinate_C.setChecked(True)
        self.coordinate_C.setObjectName("coordinate_C")
        self.horizontalLayout_13.addWidget(self.coordinate_C)
        self.coordinate_R = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.coordinate_R.setEnabled(False)
        self.coordinate_R.setObjectName("coordinate_R")
        self.horizontalLayout_13.addWidget(self.coordinate_R)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.tabWidget333.addTab(self.table_3, "")
        self.pushButton = QtWidgets.QPushButton(VASP_Set)
        self.pushButton.setGeometry(QtCore.QRect(110, 260, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(VASP_Set)
        self.tabWidget333.setCurrentIndex(2)
        self.pushButton.clicked.connect(VASP_Set.save)
        self.ISMEAR.currentIndexChanged['QString'].connect(VASP_Set.set_MP_state)
        QtCore.QMetaObject.connectSlotsByName(VASP_Set)

    def retranslateUi(self, VASP_Set):
        _translate = QtCore.QCoreApplication.translate
        VASP_Set.setWindowTitle(_translate("VASP_Set", "VASP参数设置"))
        self.label_9.setText(_translate("VASP_Set", "离子优化算法："))
        self.IBRION.setItemText(0, _translate("VASP_Set", "无更新"))
        self.IBRION.setItemText(1, _translate("VASP_Set", "MD"))
        self.IBRION.setItemText(2, _translate("VASP_Set", "RMM-DIIS"))
        self.IBRION.setItemText(3, _translate("VASP_Set", "共轭梯度"))
        self.IBRION.setItemText(4, _translate("VASP_Set", "Damped MD"))
        self.IBRION.setItemText(5, _translate("VASP_Set", "有限差分"))
        self.IBRION.setItemText(6, _translate("VASP_Set", "密度函数扰动理论"))
        self.label_10.setText(_translate("VASP_Set", "最大离子迭代步数："))
        self.label_11.setText(_translate("VASP_Set", "离子迭代收敛判据："))
        self.EDIFFG.setText(_translate("VASP_Set", "1e-3"))
        self.label_16.setText(_translate("VASP_Set", "交换关联泛函："))
        self.PBE.setItemText(0, _translate("VASP_Set", "PE"))
        self.PBE.setItemText(1, _translate("VASP_Set", "91"))
        self.PBE.setItemText(2, _translate("VASP_Set", "RP"))
        self.PBE.setItemText(3, _translate("VASP_Set", "PS"))
        self.PBE.setItemText(4, _translate("VASP_Set", "AM"))
        self.ISYM.setText(_translate("VASP_Set", "对称性"))
        self.ISPIN.setText(_translate("VASP_Set", "自旋极化"))
        self.label_15.setText(_translate("VASP_Set", "晶格变化自由度："))
        self.LREAL.setText(_translate("VASP_Set", "实空间投影"))
        self.LREAL_.setText(_translate("VASP_Set", "倒易空间投影"))
        self.tabWidget333.setTabText(self.tabWidget333.indexOf(self.tab), _translate("VASP_Set", "离子优化"))
        self.groupBox.setTitle(_translate("VASP_Set", "初始电荷密度和波函数"))
        self.label.setText(_translate("VASP_Set", "<html><head/><body><p>初始波函数：</p></body></html>"))
        self.ISTART.setItemText(0, _translate("VASP_Set", "根据INIWAV初始化波函数"))
        self.ISTART.setItemText(1, _translate("VASP_Set", "从WAVECAR读取（重定义平面波集）"))
        self.ISTART.setItemText(2, _translate("VASP_Set", "从WAVECAR读取（平面波集不变）"))
        self.label_2.setText(_translate("VASP_Set", "<html><head/><body><p>初始电荷密度：</p></body></html>"))
        self.ICHARG.setItemText(0, _translate("VASP_Set", "由初始波函数计算电荷密度"))
        self.ICHARG.setItemText(1, _translate("VASP_Set", "从CHGCAR文件读取电荷密度"))
        self.ICHARG.setItemText(2, _translate("VASP_Set", "使用原子电荷密度的叠加"))
        self.label_5.setText(_translate("VASP_Set", "电子极小化算法："))
        self.ALGO.setItemText(0, _translate("VASP_Set", "Normal"))
        self.ALGO.setItemText(1, _translate("VASP_Set", "Fast"))
        self.ALGO.setItemText(2, _translate("VASP_Set", "VeryFast"))
        self.ALGO.setItemText(3, _translate("VASP_Set", "All"))
        self.ALGO.setItemText(4, _translate("VASP_Set", "Damped"))
        self.label_7.setText(_translate("VASP_Set", "最大自洽迭代步数："))
        self.label_6.setText(_translate("VASP_Set", "最小步数："))
        self.label_14.setText(_translate("VASP_Set", "平面波截断动能："))
        self.ENCUT.setText(_translate("VASP_Set", "400"))
        self.label_12.setText(_translate("VASP_Set", "eV"))
        self.label_8.setText(_translate("VASP_Set", "自洽迭代能量收敛判据："))
        self.EDIFF.setText(_translate("VASP_Set", "1e-4"))
        self.tabWidget333.setTabText(self.tabWidget333.indexOf(self.tab_2), _translate("VASP_Set", "电子优化"))
        self.groupBox_4.setTitle(_translate("VASP_Set", "态密度积分参数"))
        self.label_13.setText(_translate("VASP_Set", "展宽方法："))
        self.ISMEAR.setItemText(0, _translate("VASP_Set", "带有Blochl修正的四面体方法"))
        self.ISMEAR.setItemText(1, _translate("VASP_Set", "不带Blochl修正的四面体方法"))
        self.ISMEAR.setItemText(2, _translate("VASP_Set", "根据INCAR文件的smearing参数循环"))
        self.ISMEAR.setItemText(3, _translate("VASP_Set", "从WAVECAR文件中读取"))
        self.ISMEAR.setItemText(4, _translate("VASP_Set", "Fermi-smearing"))
        self.ISMEAR.setItemText(5, _translate("VASP_Set", "Gaussian smearing"))
        self.ISMEAR.setItemText(6, _translate("VASP_Set", "method of Methfessel-Paxton"))
        self.label_17.setText(_translate("VASP_Set", "展宽宽度："))
        self.SIGMA.setText(_translate("VASP_Set", "0.2"))
        self.label_18.setText(_translate("VASP_Set", "eV"))
        self.label_23.setText(_translate("VASP_Set", "MP阶数："))
        self.MP_order.setText(_translate("VASP_Set", "1"))
        self.label_21.setText(_translate("VASP_Set", "色散修正："))
        self.IVDW.setItemText(0, _translate("VASP_Set", "无修正"))
        self.IVDW.setItemText(1, _translate("VASP_Set", "DFT-D2"))
        self.IVDW.setItemText(2, _translate("VASP_Set", "DFT-D3(0阻尼)"))
        self.IVDW.setItemText(3, _translate("VASP_Set", "DFT-D3(BJ)"))
        self.IVDW.setItemText(4, _translate("VASP_Set", "DFT-TS"))
        self.IVDW.setItemText(5, _translate("VASP_Set", "DFT-TS/HI"))
        self.IVDW.setItemText(6, _translate("VASP_Set", "多体能量色散"))
        self.IVDW.setItemText(7, _translate("VASP_Set", "dDsC色散修正"))
        self.label_22.setText(_translate("VASP_Set", "输出内容详细程度："))
        self.label_24.setText(_translate("VASP_Set", "核数："))
        self.label_26.setText(_translate("VASP_Set", "VASP路径："))
        self.tabWidget333.setTabText(self.tabWidget333.indexOf(self.tab_3), _translate("VASP_Set", "其它"))
        self.label_20.setText(_translate("VASP_Set", "生成方式："))
        self.generate_method.setItemText(0, _translate("VASP_Set", "自动"))
        self.generate_method.setItemText(1, _translate("VASP_Set", "全手动"))
        self.generate_method.setItemText(2, _translate("VASP_Set", "半手动/线形模式"))
        self.label_19.setText(_translate("VASP_Set", "k点个数："))
        self.coordinate_C.setText(_translate("VASP_Set", "直角坐标"))
        self.coordinate_R.setText(_translate("VASP_Set", "倒易坐标"))
        self.tabWidget333.setTabText(self.tabWidget333.indexOf(self.table_3), _translate("VASP_Set", "k-points"))
        self.pushButton.setText(_translate("VASP_Set", "保存"))

        
    def set_MP_state(self):
        '''选用method of Methfessel-Paxton order N则使用用户给定的值'''
        if self.ISMEAR.currentIndex() == 6:
            self.MP_order.setEnabled(True)
        else:
            self.MP_order.setEnabled(False)
        
        
    def save(self):
        #写INCAR文件
        param_incar = {}
        work_folder = '.'
        incar_file = open(work_folder + '/INCAR','w')
        
        #离子优化算法
        #候选值：无更新, MD, RMM-DIIS, 共轭梯度, Damped MD, 有限差分
        #计算单点能选无更新
        param_incar['IBRION'] = self.IBRION.currentIndex() - 1
        #最大离子迭代步数
        param_incar['NSW'] = self.NSW.text()
        #离子迭代收敛判据
        param_incar['EDIFFG'] = self.EDIFFG.text()
        #交换关联泛函
        param_incar['GGA'] = self.PBE.currentText()
        #对称性
        param_incar['ISYM'] = 2 if self.ISYM.isChecked() else 0 #暂时只支持0和2两个值
        #自旋极化
        param_incar['ISPIN'] = 2 if self.ISPIN.isChecked() else 1
        #晶格变化自由度
        param_incar['ISIF'] = self.ISIF.text()
        #投射是在实空间还是倒易空间进行
        param_incar['LREAL'] = '.TRUE.' if self.LREAL.isChecked() else '.FALSE.'
        
        #电子极小化算法
        #取值：Normal(blocked Davidson block iteration scheme)/VeryFast(RMM-DIIS)/Fast (前两个算法的混合)/All(波函数的所有带同时更新)/Damped(damped velocity friction algorithm)
        #缺省值: Normal
        param_incar['ALGO'] = self.ALGO.currentText()
        #最大自洽迭代步数
        param_incar['NELM'] = self.NELM.text()
        #最小自洽迭代步数
        param_incar['NELMIN'] = self.NELMIN.text()
        #平面波截断动能
        param_incar['ENCUT'] = self.ENCUT.text() + ' eV'
        #自洽迭代能量收敛判据
        param_incar['EDIFF'] = self.EDIFF.text()
        #初始波函数
        param_incar['ISTART'] = self.ISTART.currentIndex()
        #初始电荷密度
        #候选值：由初始波函数计算电荷密度，从CHGCAR文件读取电荷密度，使用原子电荷密度的叠加，+10 非自洽计算
        param_incar['ICHARG'] = self.ICHARG.currentIndex()
        #展宽方法
        #候选值：-5带有Blochl修正的四面体方法, -4不带Blochl修正的四面体方法, -3根据INCAR文件中提供的smearing参数执行循环，-2从WAVECAR文件中读取, -1Fermi-smearing, 0Gaussian smearing, >0method of Methfessel-Paxton order N
        #缺省值：1
        param_incar['ISMEAR'] = self.ISMEAR.currentIndex() - 5
        if param_incar['ISMEAR'] == 1:
            param_incar['ISMEAR'] = self.MP_order.text()
        #展宽宽度
        param_incar['SIGMA'] = self.SIGMA.text()
        #色散修正
        IVDW_list = {u'无修正':0, 'DFT-D2':1, u'DFT-D3(0阻尼)':11, 'DFT-D3(BJ)':12, 'DFT-TS':2, 'DFT-TS/HI':21, u'多体能量色散':202, u'dDsC色散修正':4}
        param_incar['IVDW'] = IVDW_list[self.IVDW.currentText()]
        #是否把波函数（或电荷密度）写入外部文件WAVECAR（或CHGCAR和CHG）中
        param_incar['LWAVE'] = '.FALSE.'
        #是否把波函数（或电荷密度）写入外部文件
        param_incar['LCHARG'] = '.FALSE.'
        
        incar_file.write('SYSTEM = CGA_temp\n')
        for k,v in param_incar.items():
            incar_file.write('%s = %s\n' %(k,v))
            
        #写KPOINTS文件
        kpoints_file = open(work_folder + '/KPOINTS','w')
        kpoints_file.write('''Monkhorst Pack
0
M
 1    1    1
 0    0    0''')
 
        """if generate_method.currentText() == u'自动':
            kpoints_file.write('Automatic generation\n')
            kpoints_file.write('0\n') #自动生成则k点数为0
        elif generate_method.currentText() == u'全手动':
            kpoints_file.write('k-points entered manually\n')
            kpoints_file.write('self.k_num.text()\n')
            kpoints_file.write('M\n')
        else:
            kpoints_file.write('k-points along high symmetry lines\n')"""
            
        cfg = ConfigParser()
        if os.path.isfile('config.ini'):
            cfg.read('config.ini')
        if not os.path.isfile('config.ini') or 'abinitio' not in cfg.sections():
            cfg.add_section('abinitio')
        cfg.set('abinitio', 'core_num', self.core_num.text())
        cfg.set('abinitio', 'vasp_path', self.vasp_path.text())
        cfg.set('abinitio', 'method', 'vasp')
        f = open('config.ini', 'w')
        cfg.write(f)
        Abinitio.config()
        
        self.close()

